# Generated by Django 4.2.11 on 2024-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_images', verbose_name='Image'),
        ),
    ]
