# Generated by Django 4.2.11 on 2024-04-18 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0002_alter_tweets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
