# Generated by Django 4.2.11 on 2024-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sphere',
            field=models.CharField(blank=True, max_length=35, verbose_name='Sphere'),
        ),
    ]
