# Generated by Django 4.2.11 on 2024-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
